name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mgred/asciidoctor-action@master
      with:
        args: asciidoctor -r asciidoctor-pdf -b pdf cv.adoc
