name: PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://asciidoctor/docker-asciidoctor:latest
      with:
        args: asciidoctor-pdf cv.adoc
