name: PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://asciidoctor/docker-asciidoctor:latest
      with:
        args: asciidoctor-pdf cv.adoc
    - uses: actions/upload-artifact@v1
      with:
        name: cv_igor_botian.pdf
        path: cv.pdf